server:
  port: 8081

# DB 연결
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://cracker-database.cohjhikof3c8.ap-northeast-2.rds.amazonaws.com:3306/cracker?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: cracker!1765

  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 10
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update

  thymeleaf:
    prefix: classpath:/templates/


# cors policy
cors:
  allowed-origins: https://crackers.life
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: \*
  exposed-headers: Set-Cookie
  max-age: 3600

# jwt secret key
jwt:
  secret: 'secretkeyforspartaprojectcracker'

app:
  auth:
    guestExpiry: 10800000
    tokenExpiry: 10800000            # 3??
    refreshTokenExpiry: 604800000    # 7?
    adminToken: TODO

  message: Message has been sent Successfully..

# kakao 로그인 REST API 키
kakao:
  secret: c68ff2766979dad52191b316a0b99f22
  adminToken: b0f4cc083b3493de772e56d92cc5bdbe


# AWS S3
cloud:
  aws:
    credentials:
      accesskey: AKIAWWHMVBI5FRDS3YPP
      secretkey: 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
    s3:
      bucket: crackertest
    region:
      static: ap-northeast-2
    stack:
      auto: false
