server:
  port: 8080

# DB 연결
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${CRACKER_DB_URL}
    username: ${CRACKER_DB_USER_NAME}
    password: ${CRACKER_DB_PASSWORD}

  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 10
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update

  thymeleaf:
    prefix: classpath:/templates/


# cors policy
cors:
  allowed-origins: http://localhost:8080
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: \*
  exposed-headers: Set-Cookie
  max-age: 3600

# jwt secret key
jwt:
  secret: ${JWT_SECRET}

app:
  auth:
    guestExpiry: 10800000
    tokenExpiry: 10800000            # 3??
    refreshTokenExpiry: 604800000    # 7?
    adminToken: ${APP_AUTH_ADMIN_TOKEN}
    cookieDomain : localhost

  message: Message has been sent Successfully..

# kakao 로그인 REST API 키
kakao:
  secret: ${KAKAO_SECRET}
  adminToken: ${KAKAO_ADMIN_TOKEN}


# AWS S3
cloud:
  aws:
    credentials:
      accesskey: ${CLOUD_AWS_CRDENTIALS_ACCESSKEY}
      secretkey: ${CLOUD_AWS_CRDENTIALS_SECRETKEY}
    s3:
      bucket: ${CLOUD_AWS_S3_BUCKET}
    region:
      static: ap-northeast-2
    stack:
      auto: false