server:
  port: 8081

# DB 연결
spring:
  datasource:
    driver-class-name: com.amazonaws.secretsmanager.sql.AWSSecretsManagerMySQLDriver
    url: jdbc-secretsmanager:mysql://cracker-database.cohjhikof3c8.ap-northeast-2.rds.amazonaws.com:3306/cracker?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: /secret/cracker/db
    password: /secret/cracker/db

  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 10
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update

  thymeleaf:
    prefix: classpath:/templates/


# cors policy
cors:
  allowed-origins: https://crackers.life
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: \*
  exposed-headers: Set-Cookie
  max-age: 3600

# jwt secret key
jwt:
  secret: /secret/cracker/key

app:
  auth:
    guestExpiry: 10800000
    tokenExpiry: 10800000            # 3??
    refreshTokenExpiry: 604800000    # 7?
    adminToken: /secret/cracker/key
    cookieDomain : /secret/cracker/key

  message: Message has been sent Successfully..

# kakao 로그인 REST API 키
kakao:
  secret: /secret/cracker/key
  adminToken: /secret/cracker/key


# AWS S3
cloud:
  aws:
    credentials:
      accesskey: /secret/cracker/key
      secretkey: /secret/cracker/key
    s3:
      bucket: crackertest
    region:
      static: ap-northeast-2
    stack:
      auto: false
