server:
  port: 8080

spring:
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
#    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:h2:tcp://localhost/~/test
#    url: jdbc:mysql://localhost:3306/cracker?serverTimezone=Asia/Seoul
    username: sa
    password:
  thymeleaf:
    prefix: classpath:/templates/
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
#  application:
#    name: certification-service
#
#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher

# cors policy
cors:
  allowed-origins: http://localhost:8080
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: \*
  exposed-headers: Set-Cookie
  max-age: 3600

# jwt secret key
jwt:
  secret: 'secretkeyforspartaprojectcracker'

app:
  auth:
    tokenExpiry: 10800000            # 3??
    refreshTokenExpiry: 604800000    # 7?
    adminToken: TODO

  message: Message has been sent Successfully..

# kakao 로그인 REST API 키
kakao:
  secret: c68ff2766979dad52191b316a0b99f22
  adminToken: b0f4cc083b3493de772e56d92cc5bdbe

#logging:
#  level:
#    root: DEBUG